[FISH-1112] Payara 5.26.0 Release Docs
payara/Payara-Enterprise-Documentation pull request #129
Opened 2021-03-06 20:55 UTC by lprimak

2021-03-07 18:24 UTC, rdebusscher requested changes

2021-03-07 18:24 UTC, rdebusscher commented on docs/modules/ROOT/pages/jakartaee-certification/5.26.0/tck-results-web-5.26.0.adoc
> +[INFO] --- maven-surefire-report-plugin:2.21.0:report-only (generate-test-report) @ hibernate-validator-tck-runner ---
This and the following line can be removed

2021-03-07 18:24 UTC, rdebusscher commented on docs/modules/ROOT/pages/jakartaee-certification/5.26.0/tck-results-web-5.26.0.adoc
> + [mvn.test] [INFO] --- maven-surefire-report-plugin:2.19.1:report-only (generate-test-report) @ weld-payara-runner-tck11 ---
This and the following line can be removed

2021-03-07 18:24 UTC, rdebusscher commented on docs/modules/ROOT/pages/jakartaee-certification/5.26.0/tck-results-full-5.26.0.adoc
> +[INFO] --- maven-surefire-report-plugin:2.21.0:report-only (generate-test-report) @ hibernate-validator-tck-runner ---
This and the following line can be removed

2021-03-07 18:24 UTC, rdebusscher commented on docs/modules/ROOT/pages/jakartaee-certification/5.26.0/tck-results-full-5.26.0.adoc
> + [mvn.test] [INFO] --- maven-surefire-report-plugin:2.19.1:report-only (generate-test-report) @ weld-payara-runner-tck11 ---
This and the following line can be removed

2021-03-07 18:24 UTC, rdebusscher commented on docs/modules/ROOT/pages/jakartaee-certification/5.26.0/tck-results-full-5.26.0.adoc
> +[INFO] Tests run: 1043, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 658.032 s - in TestSuite
Missing indentation

2021-03-07 18:24 UTC, rdebusscher commented on docs/modules/ROOT/pages/jakartaee-certification/5.26.0/tck-results-web-5.26.0.adoc
> +[INFO] Tests run: 1043, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 632.077 s - in TestSuite
Missing indentation

2021-03-07 18:35 UTC, lprimak commented
@rdebusscher this is a paste of a generated file. Do you really want me to make these changes?  I don’t think that’s sustainable going forward and not documented anywhere. 
I am just following what’s on confluence which is very involved as it is.

2021-03-08 06:39 UTC, rdebusscher commented
@lprimak I compared it to the TCK result presentation of the previous releases.  We can do this also in a separate PR.

2021-03-08 06:48 UTC, rdebusscher approved these changes
Content OK, Small layout improvements later

2021-03-08 10:53 UTC, Pandrex247 approved these changes
Aside from Rudy's comments LGTM

2021-03-08 21:22 UTC, merged