[FISH-1259] - Payara 5.27.0 Release Notes
payara/Payara-Enterprise-Documentation pull request #139
Opened 2021-03-31 10:51 UTC by cubastanley

TCK results to come in later PR

2021-04-01 08:45 UTC, Pandrex247 approved these changes

2021-04-01 12:26 UTC, rdebusscher requested changes
Within the menu navigation on the left (nav.adoc) there is still the link to the 5.26.0 release notes.  (General Info -> Introduction -> Release Notes)

2021-04-01 12:26 UTC, rdebusscher commented on docs/modules/ROOT/pages/jakartaee-certification/5.27.0/README.adoc
> +The following distributions of Payara 5.25.0 are certified:
Wrong Links! (to the 5.25.0 TCK results)

2021-04-01 15:36 UTC, lprimak approved these changes

2021-04-02 13:50 UTC, rdebusscher approved these changes

2021-04-06 10:58 UTC, merged