FISH-1498: Client Certificate Validation documentation
payara/Payara-Enterprise-Documentation pull request #153
Opened 2021-06-10 11:56 UTC by rdebusscher

2021-06-18 04:09 UTC, lprimak requested changes
one slight word change and one-character syntax fix

2021-06-18 04:09 UTC, lprimak commented on docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/certificate-realm-certificate-validation.adoc
> +NOTE: Since the class is loaded through the Java ServiceLoader mechanism, you cannot object CDI or EJB beans into it. You can retrieve an instance of a CDI bean using  `CDI.current().select(MyCDIBean
object -> inject

2021-06-18 04:38 UTC, lprimak commented on docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/certificate-realm-certificate-validation.adoc
> +            <version>{currentVersion}/version>
missing '<' in front of `</version>`

2021-06-18 09:58 UTC, rdebusscher commented
Thx @lprimak! Updated according your remarks.

2021-06-18 11:24 UTC, AlanRoth commented
I left some requests for changes on the Community version of this documentation, if they are implemented can they be reflected in the Enterprise documentation also to keep everything consistent

2021-06-18 13:46 UTC, lprimak approved these changes

2021-06-18 17:45 UTC, rdebusscher commented
@AlanRoth Updated according your comments on community documentation PR

2021-06-22 08:23 UTC, AlanRoth approved these changes

2021-06-22 08:26 UTC, merged