FISH-667 MicroProfile 4.1
payara/Payara-Enterprise-Documentation pull request #154
Opened 2021-06-11 10:01 UTC by Pandrex247

Title.
Main PR: https://github.com/payara/Payara-Enterprise/pull/398

2021-06-11 13:05 UTC, rdebusscher requested changes

2021-06-11 13:05 UTC, rdebusscher commented on docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
> +_Since Payara Platform 5.2020.7_
Community Number

2021-06-11 13:06 UTC, rdebusscher commented on docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
> +_Since Payara Platform 5.2020.7_
I was looking at the previous version of the PR :)

2021-06-11 13:07 UTC, rdebusscher approved these changes

2021-06-17 08:31 UTC, AlanRoth requested changes

2021-06-17 08:31 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
> +_Since Payara Platform 5.23.1_
We don't need to include the 'Since Payara' no more

2021-06-17 08:31 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
> +_Since Payara Platform 5.184_
We don't need to include the 'Since Payara' no more

2021-06-17 08:31 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
> +NOTE: Since Payara Platform 5.29.0, the options `asyncmaxpoolsize` and `delaymaxpoolsize` have been removed as they are no longer applicable due to the configurable managed executor pools being used.
I'll let this one pass

2021-06-17 08:31 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
>  Since 5.192 the Payara specific configuration property `MP_Fault_Tolerance_Alternative_Asynchronous_Annotations` can be used to specify a comma separated list of fully qualified class names of those
Might as well get rid of the 'since 5.192' too to keep everything consistent.

2021-06-23 13:49 UTC, AlanRoth approved these changes

2021-06-23 14:05 UTC, lprimak approved these changes

2021-06-23 14:33 UTC, Pandrex247 commented
Rebased ontop of https://github.com/payara/Payara-Enterprise-Documentation/pull/158

2021-07-05 14:35 UTC, Pandrex247 commented
Rebased ontop of https://github.com/payara/Payara-Enterprise-Documentation/pull/158 again

2021-07-06 08:45 UTC, AlanRoth commented
Just a note - could you remove any 'Since Payara' tags on the top of pages you edited?

2021-08-05 09:52 UTC, closed without merging