FISH-651 FISH-868 FISH-1372 FISH-1504 FISH-1526 MicroProfile 4.0
payara/Payara-Enterprise-Documentation pull request #158
Opened 2021-06-23 14:31 UTC by Pandrex247

Split off from https://github.com/payara/Payara-Enterprise-Documentation/pull/154

Title.
Main PR: https://github.com/payara/Payara-Enterprise/pull/407

Also brings across payara/Payara-Community-Documentation#115, since this seems to have been missed.
Also brings across payara/Payara-Community-Documentation#127, since this seems to have been missed.

2021-07-02 19:07 UTC, OndroMih requested changes
I added some suggestions in comments and also created a PR https://github.com/Pandrex247/Payara-Enterprise-Documentation/pull/2 with some more suggestions.

2021-07-05 08:09 UTC, Pandrex247 commented on docs/modules/ROOT/pages/documentation/microprofile/healthcheck.adoc
>  |`/health`
It already has that?

2021-07-05 08:10 UTC, Pandrex247 commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
>  [cols="4,10,1,1", options="header"]
Already has that?

2021-07-05 14:33 UTC, Pandrex247 commented
Added additional docs pertaining to upgrade issues.

2021-07-06 08:47 UTC, AlanRoth approved these changes
Looks good, however, like my comment on #154, please remove any 'Since Payara' tags you see on pages you edited, the tag is deprecated on any pages going forward

2021-07-07 10:51 UTC, merged