FISH-651 FISH-868 FISH-1504 FISH-1526 FISH-1527 Revert MicroProfile 4.0
payara/Payara-Enterprise-Documentation pull request #166
Opened 2021-07-15 16:43 UTC by Pandrex247

This reverts https://github.com/payara/Payara-Enterprise-Documentation/pull/158

2021-07-15 21:22 UTC, OndroMih requested changes
The duplicate JSON-P references don't have to be reverted too. Otherwise all looks good.

2021-07-15 21:22 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/README.adoc
> +* JSON-P 1.1
```suggestion
```

2021-07-15 21:22 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/README.adoc
> +* JSON-P 1.1
```suggestion
```

2021-07-15 21:22 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/README.adoc
> +* JSON-P 1.1
```suggestion
```

2021-07-16 09:57 UTC, AlanRoth approved these changes
Just these nit picks

2021-07-16 09:57 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
> +Since 5.192 the Payara specific configuration property `MP_Fault_Tolerance_Alternative_Asynchronous_Annotations` can be used to specify a comma separated list of fully qualified class names of those
```suggestion
The the Payara specific configuration property `MP_Fault_Tolerance_Alternative_Asynchronous_Annotations` can be used to specify a comma separated list of fully qualified class names of those annotations that should have the same effect as FT's `@Asynchronous`. These annotations do not have to be interceptor bindings.
```
I think we don't need to revert this bit

2021-07-16 09:57 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
> +NOTE: Since Payara Platform Enterprise 5.20.0, the configuration no longer allows configuring user defined executor to run the fault tolerance execution. Instead, Fault Tolerance uses two dedicated e
```suggestion
NOTE: The configuration no longer allows configuring user defined executor to run the fault tolerance execution. Instead, Fault Tolerance uses two dedicated executors that are well suited for the usage pattern typically experienced when executing Fault Tolerance semantics. It's possible to configure the maximum size of these pools to scale them up or down.
```

2021-07-16 09:57 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
> +_Since Payara Micro 5.184_
```suggestion
```

2021-07-19 08:28 UTC, merged