FISH-651 FISH-666 FISH-667 FISH-868 FISH-1372 FISH-1504 FISH-1526 FISH-1527 MicroProfile 4.0 & 4.1
payara/Payara-Enterprise-Documentation pull request #173
Opened 2021-08-05 10:28 UTC by Pandrex247

Revert of https://github.com/payara/Payara-Enterprise-Documentation/pull/166 and merge of https://github.com/payara/Payara-Enterprise-Documentation/pull/154

Main PR: https://github.com/payara/Payara-Enterprise/pull/433
TCK Runners PR: https://github.com/payara/MicroProfile-TCK-Runners/pull/147 and https://github.com/payara/MicroProfile-TCK-Runners/pull/152

2021-08-06 13:30 UTC, OndroMih requested changes

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
>  ==== `set-fault-tolerance-configuration`
```suggestion
[[set-fault-tolerance-configuration]]
==== `set-fault-tolerance-configuration`
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
>  ===== Command Options
```suggestion
[[set-fault-tolerance-configuration-options]]
===== Command Options
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
>  ===== Example
```suggestion
[[set-fault-tolerance-configuration-example]]
===== Example
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
>  ==== `get-fault-tolerance-configuration`
```suggestion
[[get-fault-tolerance-configuration]]
==== `get-fault-tolerance-configuration`
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
>  ===== Command Options
```suggestion
[[get-fault-tolerance-configuration-options]]
===== Command Options
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
> +=== Metric Names and Scopes Changed
```suggestion
[[names-and-scopes-changed]]
=== Metric Names and Scopes Changed
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
> +==== Example
```suggestion
[[names-and-scopes-changed-example]]
==== Example
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
> +=== Lifecycle of CircuitBreakers and Bulkheads Specified
```suggestion
[[lifecycle-specified]]
=== Lifecycle of CircuitBreakers and Bulkheads Specified
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
>  === Namespaced claims configuration
```suggestion
[[namespaced-claims-configuration]]
=== Namespaced claims configuration
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
>  ==== *custom.namespace*
```suggestion
[[custom-namespace]]
==== *custom.namespace*
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
> +=== Disabling Type Claim Verification
```suggestion
[[disabling-type-claim-verification]]
=== Disabling Type Claim Verification
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
> +=== Caching the Public Key
```suggestion
[[caching-public-key]]
=== Caching the Public Key
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
> +NOTE: This property has to be defined in the `payara-mp-jwt.properties` configuration file described in the previous section.
```suggestion
NOTE: This property has to be defined in the `payara-mp-jwt.properties` configuration file described in the previous section.

```

A space between NOTE and the next header to fix the formatting

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
>  == Activating JWT Authentication
```suggestion
[[activating-jwt]]
== Activating JWT Authentication
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/metrics.adoc
> +=== All Metrics Now Reusable
```suggestion
[[upgrade-to-4-metrics-reusable]]
=== All Metrics Now Reusable
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/metrics.adoc
> +===  MetadataBuilder.withOptional* Methods Removed
```suggestion
[[upgrade-to-4-with-optional-removed]]
===  MetadataBuilder.withOptional* Methods Removed
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/metrics.adoc
> +=== Metadata.getDescription() and Metadata.getUnit() Return Type Changed
```suggestion
[[upgrade-to-4-return-type-changed]]
=== Metadata.getDescription() and Metadata.getUnit() Return Type Changed
```

2021-08-06 13:30 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/microprofile/metrics.adoc
> +=== Timer.update(long duration, TimeUnit unit) Removed
```suggestion
[[upgrade-to-4-timer-methods-removed]]
=== Timer.update(long duration, TimeUnit unit) Removed
```

2021-08-10 13:15 UTC, MarkWareham commented on docs/modules/ROOT/pages/documentation/microprofile/config/README.adoc
> +with the previous version of MicroProfile Config, though one is only important when writing your own _ConfigSources_.
This doesnt make alot of sense to me. Seems like a fragment of information.

2021-08-10 13:22 UTC, MarkWareham approved these changes
LGTM

2021-08-10 13:30 UTC, merged