[QACI-5504] - 5.30.0 Release Notes + TCK Results
payara/Payara-Enterprise-Documentation pull request #177
Opened 2021-08-13 15:40 UTC by cubastanley

Title

2021-08-13 17:03 UTC, debbiehoffman requested changes

2021-08-13 17:03 UTC, debbiehoffman commented on docs/modules/ROOT/pages/release-notes/release-notes-30-0.adoc
> += Release notes - Payara Platform Development - Version 5.30.0
Please change to:

Release Notes - Payara Platform Enterprise 5.30.0

2021-08-13 17:03 UTC, debbiehoffman commented on docs/modules/ROOT/pages/release-notes/release-notes-30-0.adoc
> +* [FISH-1068] - Parameter Serialization error in open api document for query parameter
I think this should be:

OpenAPI  (all one word and with capitals)

2021-08-13 17:03 UTC, debbiehoffman commented on docs/modules/ROOT/pages/release-notes/release-notes-30-0.adoc
> +* [FISH-1204] - Missing example values in OpenApi components schema definition using nested objects
I think it should be:
OpenAPI
(all one word and with capitals)

2021-08-16 08:59 UTC, Pandrex247 requested changes
I feel like there should be some words at the top of the release notes highlighting that the upgrade from MicroProfile 3.3 to 4.1 introduces breaking changes.

2021-08-16 08:59 UTC, Pandrex247 commented on docs/modules/ROOT/pages/release-notes/release-notes-30-0.adoc
> +* [FISH-1526] - Upgrade Payara Enterprise to MicroProfile 4.0
Should get changed to 4.1 - not 4.0

2021-08-16 08:59 UTC, Pandrex247 commented on docs/modules/ROOT/pages/release-notes/release-notes-30-0.adoc
> +* [FISH-1372] - MicroProfile Health 3.1
Not sure this is worth mentioning? It's a part of MicroProfile 4.1 - it's not a standalone feature.

2021-08-16 10:38 UTC, Pandrex247 requested changes

2021-08-16 10:38 UTC, Pandrex247 commented on docs/modules/ROOT/pages/release-notes/release-notes-30-0.adoc
> +* [FISH-1526] - Upgrade Payara Enterprise to MicroProfile 4.1
Sorry, I wasn't clear - I meant that this should get replaced with the MP 4.1 issue, not just changing the number.
```suggestion
* [FISH-666] - Upgrade Payara Enterprise to MicroProfile 4.1
```

2021-08-16 11:01 UTC, Pandrex247 approved these changes

2021-08-16 14:38 UTC, debbiehoffman approved these changes

2021-08-16 14:41 UTC, rdebusscher approved these changes

2021-08-16 14:52 UTC, merged