H2 Console Vulnerability
payara/Payara-Enterprise-Documentation pull request #224
Opened 2022-01-13 09:53 UTC by OndroMih

2022-01-13 10:36 UTC, rdebusscher requested changes

2022-01-13 10:36 UTC, rdebusscher commented on docs/modules/ROOT/pages/security/security-fix-list.adoc
> +|https://nvd.nist.gov/vuln/detail/CVE-2021-42392[CVE-2021-42392] | N/A | N/A | Unauthenticated RCE in H2 Database Console |  | Unrelated to Payara Server. H2 Database Console doesn't launch the H2 Da
Sentence doesn't seems to be correct

**H2 Database Console** doesn't launch the **H2 Database Console** ...

2022-01-13 11:24 UTC, OndroMih commented on docs/modules/ROOT/pages/security/security-fix-list.adoc
> +|https://nvd.nist.gov/vuln/detail/CVE-2021-42392[CVE-2021-42392] | N/A | N/A | Unauthenticated RCE in H2 Database Console |  | Unrelated to Payara Server. H2 Database Console doesn't launch the H2 Da
You're right, I'll fix it.
```suggestion
|https://nvd.nist.gov/vuln/detail/CVE-2021-42392[CVE-2021-42392] | N/A | N/A | Unauthenticated RCE in H2 Database Console |  | Unrelated to Payara Platform. The Payara Platform doesn't launch the H2 Database Console and doesn't make it available in any way.
```

2022-01-14 22:32 UTC, fturizo approved these changes
Looks good, I'd change the "Unrelated to Payara Platform" to "Doesn't affect Payara Platform" so that the message is clearer.

2022-01-19 10:49 UTC, OndroMih commented on docs/modules/ROOT/pages/security/security-fix-list.adoc
> +|https://nvd.nist.gov/vuln/detail/CVE-2021-42392[CVE-2021-42392] | N/A | N/A | Unauthenticated RCE in H2 Database Console |  | Unrelated to Payara Platform. The Payara Platform doesn't launch the H2
```suggestion
|https://nvd.nist.gov/vuln/detail/CVE-2021-42392[CVE-2021-42392] | N/A | N/A | Unauthenticated RCE in H2 Database Console |  | Doesn't affect Payara Platform. The Payara Platform doesn't launch the H2 Database Console and doesn't make it available in any way.
```

2022-01-19 10:50 UTC, merged