FISH-244 Document Tracing of Remote EJBs
payara/Payara-Enterprise-Documentation pull request #55
Opened 2020-10-05 11:41 UTC by Pandrex247

Port of https://github.com/payara/Payara-Community-Documentation/pull/54

2020-10-06 10:59 UTC, OndroMih requested changes

2020-10-06 10:59 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/payara-server/request-tracing-service/tracing-remote-ejbs.adoc
> +[[tracing-remote-ejbs]]
This new file needs to be added to nav.adoc, otherwise it's not visible in the generated documentation.

2020-10-07 08:58 UTC, Pandrex247 commented
Opened a PR to make the requested changes on community too.

2020-10-07 10:00 UTC, OndroMih requested changes

2020-10-07 10:00 UTC, OndroMih commented on docs/modules/ROOT/nav.adoc
> +*** xref:documentation/payara-server/request-tracing-service/tracing-remote-ejbs.adoc[Terminology]
```suggestion
*** xref:documentation/payara-server/request-tracing-service/tracing-remote-ejbs.adoc[Tracing remote EJBs]
```

2020-10-07 11:47 UTC, Pandrex247 commented on docs/modules/ROOT/nav.adoc
> +*** xref:documentation/payara-server/request-tracing-service/tracing-remote-ejbs.adoc[Terminology]
🤦‍♂️

2020-10-07 12:47 UTC, OndroMih approved these changes

2020-10-07 12:47 UTC, merged