[FISH-807] - Payara Enterprise 5.23.1 Release Notes
payara/Payara-Enterprise-Documentation pull request #85
Opened 2020-12-04 15:20 UTC by cubastanley

Release notes for Payara Enterprise 5.23.1 - I noticed the previous release didn't have links to GH PRs where applicable, is this correct now or should I be adding links to this and the previous release notes?

2020-12-07 10:32 UTC, OndroMih requested changes

2020-12-07 10:32 UTC, OndroMih commented on docs/modules/ROOT/nav.adoc
> -*** xref:release-notes/release-notes-23-0.adoc[Payara Enterprise 5.23.0 Release Notes]
Please keep the link to RN of 23.o here too. We're not going to release a completely new version of the docs, we'll just update existing 5.23 docs. The pattern we use is that we just add a new page for each patch version. So there will be 2 RN pages here now: for 5.23.0 and for 5.23.1

2020-12-07 10:32 UTC, OndroMih commented on docs/modules/ROOT/nav.adoc
> +** xref:release-notes/release-notes-23.1.adoc[Payara Enterprise 5.23.1 Release Notes]
Please also add a link to the 5.23.0 RN here

2020-12-07 14:50 UTC, Pandrex247 approved these changes

2020-12-07 17:32 UTC, OndroMih commented on docs/modules/ROOT/nav.adoc
> -*** xref:release-notes/release-notes-23-0.adoc[Payara Enterprise 5.23.0 Release Notes]
@cubastanley , I think you misunderstood me. There should be now both release notes for 5.23.0 and 5.23.1 linked here. Similar to this PR for 5.21.2: https://github.com/payara/Payara-Enterprise-Documentation/pull/48/files#diff-2074dbd9f25b3a4b6f9d1f2ce74c297bd9c97be43683b94ee7c7a8e3eb6c3d6fR5. We always include RN for the latest minor version and all its patch versions here.

2020-12-08 16:12 UTC, OndroMih commented on docs/modules/ROOT/nav.adoc
> +** xref:release-notes/release-notes-23.0.adoc[Payara Enterprise 5.23.0 Release Notes]
We should remove these references because they are duplicates and Antora creates broken links for them
```suggestion
```

2020-12-08 17:19 UTC, merged